server {
  listen 80;
  root /staticfiles;
  index index.html index.htm;
  
  location /api/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/api/;
  }
  location /admin/ {
    proxy_set_header Host $http_host;
    proxy_pass http://backend:9000/admin/;
  }

  location / {
    error_page 404 = /index.html;
    try_files $uri $uri/ =404;
  }
}
